=== kuskuscz/Projekt/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="škola">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="třída" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="PSČ" type="xs:integer" use="required"/>
      <xs:attribute name="infolinka" type="xs:integer" use="required"/>
      <xs:attribute name="město" type="xs:string" use="required"/>
      <xs:attribute name="název" type="xs:string" use="required"/>
      <xs:attribute name="ulice" type="xs:string" use="required"/>
      <xs:attribute name="web" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="třída">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="žák" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
<xs:simpleType name="typPohlavi">
<xs:restriction base="xs:string">
<xs:enumeration value="muž"></xs:enumeration>
<xs:enumeration value="žena"></xs:enumeration>
</xs:restriction>
</xs:simpleType>  
  
  
  <xs:element name="žák">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jméno" type="xs:string"/>
        <xs:element name="příjmení" type="xs:string"/>
        <xs:element name="pohlaví" type="typPohlavi"/>
        <xs:element name="datNar" type="xs:date"/>
        <xs:element ref="kontaktŽák"/>
        <xs:element ref="kontaktRodič"/>
        <xs:element ref="poznámky"/>
        <xs:element ref="známky"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="kontaktŽák">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="spojení"/>
        <xs:element ref="adresa"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="spojení">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="mobil" type="xs:integer"/>
        <xs:element name="pevnáLinka" type="xs:string"/>
        <xs:element name="email" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="adresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ulice" type="xs:string"/>
        <xs:element name="město" type="xs:string"/>
        <xs:element name="PSČ" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="kontaktRodič">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="spojení"/>
        <xs:element ref="adresa"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="poznámky">
    <xs:complexType>
      <xs:sequence minOccurs="0" >
        <xs:element ref="prvnipololeti" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="druhepololeti" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="prvnipololeti">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element ref="poznámka" minOccurs="0"/>
        <xs:element ref="predmět" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="poznámka">
    <xs:complexType mixed="true">
      <xs:attribute name="datum" type="xs:date" use="required"/>
      <xs:attribute name="zadánoOd" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="druhepololeti">
    <xs:complexType>
      <xs:sequence >
        <xs:element ref="poznámka" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="predmět" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="známky">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="prvnipololeti" maxOccurs="1"/>
        <xs:element ref="druhepololeti" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="predmět">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="známka"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="známka">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="datumUdělení" type="xs:date"/>
        
        <xs:element name="hodnota">
 <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="5"/>
    </xs:restriction>
  </xs:simpleType>        
        </xs:element>
        
        <xs:element name="váha" >
        <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>        
        </xs:element>
        
        
        <xs:element name="téma" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
  
</xs:schema>

=== kuskuscz/Projekt/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transformace.xsl"?>
<škola název="Středí škola" ulice="Komenská 12" město="Praha" PSČ="11100" infolinka="225587988" web="www.skolass.cz"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
>
<třída id="1.A">
        <žák id="1">

            <jméno>Dan</jméno>
            <příjmení>Kolář</příjmení>
            <pohlaví>muž</pohlaví>
            <datNar>1998-10-05</datNar>

            <kontaktŽák>
                <spojení>
                    <mobil>755779999</mobil>
                    <pevnáLinka>235555666</pevnáLinka>
                    <email>kolar@gmail.com</email>
                </spojení>
                <adresa>
                    <ulice>Konrádova 4</ulice>
                    <město>Praha</město>
                    <PSČ>16000</PSČ>
                </adresa>
            </kontaktŽák>

            <kontaktRodič>
                <spojení>
                    <mobil>666888777</mobil>
                    <pevnáLinka>222477777</pevnáLinka>
                    <email>bbb@seznam.cz</email>
                </spojení>
                <adresa>
                    <ulice>Konrádova 4</ulice>
                    <město>Praha</město>
                    <PSČ>16000</PSČ>
                </adresa>
            </kontaktRodič>

            <poznámky>
                <prvnipololeti>
                    <poznámka datum="2016-11-04" zadánoOd="Jana Janská">Nemá tělocvik</poznámka>
                </prvnipololeti>
                <druhepololeti>
                    <poznámka datum="2017-03-01" zadánoOd="Jan Vrhel">Spí</poznámka>
                </druhepololeti>
            </poznámky>

            <známky>
                <prvnipololeti>
                    <predmět id="Čj">
                        <známka>
                            <datumUdělení>2016-12-12</datumUdělení>
                            <hodnota>2</hodnota>
                            <váha>5</váha>
                            <téma>Literatura</téma>
                        </známka>
                    </predmět>

                    <predmět id="Ma">
                        <známka>
                            <datumUdělení>2017-11-08</datumUdělení>
                            <hodnota>3</hodnota>
                            <váha>8</váha>
                            <téma>Čtrvtletní práce</téma>
                        </známka>
                    </predmět>
                </prvnipololeti>

                <druhepololeti>
                    <predmět id="Aj">
                        <známka>
                            <datumUdělení>2016-03-22</datumUdělení>
                            <hodnota>5</hodnota>
                            <váha>3</váha>
                            <téma>Travelling</téma>
                        </známka>
                    </predmět>
                </druhepololeti>

            </známky>
        </žák>









        <žák id="2">

            <jméno>Jana</jméno>
            <příjmení>Nováková</příjmení>
            <pohlaví>žena</pohlaví>
            <datNar>1999-10-05</datNar>

            <kontaktŽák>
                <spojení>
                    <mobil>755778889</mobil>
                    <pevnáLinka>235888666</pevnáLinka>
                    <email>njana@gmail.com</email>
                </spojení>
                <adresa>
                    <ulice>Konrádova 54</ulice>
                    <město>Praha</město>
                    <PSČ>16000</PSČ>
                </adresa>
            </kontaktŽák>

            <kontaktRodič>
                <spojení>
                    <mobil>666555557</mobil>
                    <pevnáLinka>255557777</pevnáLinka>
                    <email>55555@seznam.cz</email>
                </spojení>
                <adresa>
                    <ulice>Konrádova 54</ulice>
                    <město>Praha</město>
                    <PSČ>16000</PSČ>
                </adresa>
            </kontaktRodič>

            <poznámky>
                <druhepololeti>
                    <poznámka datum="2017-04-01" zadánoOd="Hana Horkelová">Nemá úkol</poznámka>
                    <poznámka datum="2017-05-01" zadánoOd="Jan Novák">Drzost</poznámka>
                </druhepololeti>
            </poznámky>

            <známky>
                <prvnipololeti>
                    <predmět id="Čj">
                        <známka>
                            <datumUdělení>2016-12-12</datumUdělení>
                            <hodnota>4</hodnota>
                            <váha>5</váha>
                            <téma>Literatura</téma>
                        </známka>
                    </predmět>

                    <predmět id="Ma">
                        <známka>
                            <datumUdělení>2017-11-08</datumUdělení>
                            <hodnota>1</hodnota>
                            <váha>8</váha>
                            <téma>Čtrvtletní práce</téma>
                        </známka>
                    </predmět>
                </prvnipololeti>

                <druhepololeti>
                    <predmět id="Aj">
                        <známka>
                            <datumUdělení>2016-03-22</datumUdělení>
                            <hodnota>2</hodnota>
                            <váha>3</váha>
                            <téma>Travelling</téma>
                        </známka>
                    </predmět>
                </druhepololeti>

            </známky>
        </žák>


        <žák id="3">

            <jméno>Adriana</jméno>
            <příjmení>Havlová</příjmení>
            <pohlaví>žena</pohlaví>
            <datNar>1999-01-05</datNar>

            <kontaktŽák>
                <spojení>
                    <mobil>752278882</mobil>
                    <pevnáLinka>235222222</pevnáLinka>
                    <email>ahavlova@seznam.cz</email>
                </spojení>
                <adresa>
                    <ulice>Alšova 55</ulice>
                    <město>Praha</město>
                    <PSČ>18000</PSČ>
                </adresa>
            </kontaktŽák>

            <kontaktRodič>
                <spojení>
                    <mobil>666777557</mobil>
                    <pevnáLinka>255777777</pevnáLinka>
                    <email>55555@seznam.cz</email>
                </spojení>
                <adresa>
                    <ulice>Alšova 55</ulice>
                    <město>Praha</město>
                    <PSČ>18000</PSČ>
                </adresa>
            </kontaktRodič>

            <poznámky>
                <prvnipololeti>
                    <poznámka datum="2016-10-01" zadánoOd="Hana Horkelová">Nepřezula se</poznámka>
                </prvnipololeti>
            </poznámky>

            <známky>
                <prvnipololeti>
                    <predmět id="Čj">
                        <známka>
                            <datumUdělení>2016-12-12</datumUdělení>
                            <hodnota>1</hodnota>
                            <váha>5</váha>
                            <téma>Literatura</téma>
                        </známka>
                    </predmět>

                    <predmět id="Ma">
                        <známka>
                            <datumUdělení>2017-11-08</datumUdělení>
                            <hodnota>1</hodnota>
                            <váha>8</váha>
                            <téma>Čtrvtletní práce</téma>
                        </známka>
                    </predmět>
                </prvnipololeti>

                <druhepololeti>
                    <predmět id="Aj">
                        <známka>
                            <datumUdělení>2016-03-22</datumUdělení>
                            <hodnota>2</hodnota>
                            <váha>1</váha>
                            <téma>Travelling</téma>
                        </známka>
                    </predmět>
                </druhepololeti>

            </známky>
        </žák>

    </třída>



    <třída id="1.B">
        <žák id="4">

            <jméno>Jan</jméno>
            <příjmení>Pilát</příjmení>
            <pohlaví>muž</pohlaví>
            <datNar>1998-01-05</datNar>

            <kontaktŽák>
                <spojení>
                    <mobil>752233382</mobil>
                    <pevnáLinka>233222222</pevnáLinka>
                    <email>pili@seznam.cz</email>
                </spojení>
                <adresa>
                    <ulice>Hektorova 188</ulice>
                    <město>Praha</město>
                    <PSČ>12000</PSČ>
                </adresa>
            </kontaktŽák>

            <kontaktRodič>
                <spojení>
                    <mobil>666777557</mobil>
                    <pevnáLinka>255777777</pevnáLinka>
                    <email>rodic@seznam.cz</email>
                </spojení>
                <adresa>
                    <ulice>Kolova 5</ulice>
                    <město>Praha</město>
                    <PSČ>17000</PSČ>
                </adresa>
            </kontaktRodič>

            <poznámky>
                <prvnipololeti>
                    <poznámka datum="2016-10-01" zadánoOd="Hana Horkelová">Nemá tělocvik</poznámka>
                </prvnipololeti>
                <druhepololeti>
                    <poznámka datum="2017-05-01" zadánoOd="Jan Výtisk">Vyrušuje</poznámka>
                </druhepololeti>
            </poznámky>

            <známky>
                <prvnipololeti>
                    <predmět id="Čj">
                        <známka>
                            <datumUdělení>2016-12-12</datumUdělení>
